module.exports = [
  'react',
  'prop-types',
  'react-dom',
  // 'react-emotion',
  // 'react-helmet',
  // 'worona-deps',
  // 'superagent',
  // 'styled-components',
  // 'redux',
  // 'redux-saga',
  // 'reselect',
  // 'react-redux',
  // 'recompose',
];
